<?php
/**
 * InventorySummaryInquiryApi
 * PHP version 5
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Crana/17.200.001
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Hut6\CranaplusAcumaticaSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Hut6\CranaplusAcumaticaSdk\ApiException;
use Hut6\CranaplusAcumaticaSdk\Configuration;
use Hut6\CranaplusAcumaticaSdk\HeaderSelector;
use Hut6\CranaplusAcumaticaSdk\ObjectSerializer;

/**
 * InventorySummaryInquiryApi Class Doc Comment
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InventorySummaryInquiryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation inventorySummaryInquiryDeleteById
     *
     * Deletes the record by its session identifier.
     *
     * @param  string $id The session ID of the record. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function inventorySummaryInquiryDeleteById($id)
    {
        $this->inventorySummaryInquiryDeleteByIdWithHttpInfo($id);
    }

    /**
     * Operation inventorySummaryInquiryDeleteByIdWithHttpInfo
     *
     * Deletes the record by its session identifier.
     *
     * @param  string $id The session ID of the record. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryDeleteByIdWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryDeleteByIdRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryDeleteByIdAsync
     *
     * Deletes the record by its session identifier.
     *
     * @param  string $id The session ID of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryDeleteByIdAsync($id)
    {
        return $this->inventorySummaryInquiryDeleteByIdAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryDeleteByIdAsyncWithHttpInfo
     *
     * Deletes the record by its session identifier.
     *
     * @param  string $id The session ID of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryDeleteByIdAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryDeleteByIdRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryDeleteById'
     *
     * @param  string $id The session ID of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryDeleteByIdRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling inventorySummaryInquiryDeleteById'
            );
        }

        $resourcePath = '/InventorySummaryInquiry/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryDeleteByKeys
     *
     * Deletes the record by the values of its key fields.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function inventorySummaryInquiryDeleteByKeys($ids)
    {
        $this->inventorySummaryInquiryDeleteByKeysWithHttpInfo($ids);
    }

    /**
     * Operation inventorySummaryInquiryDeleteByKeysWithHttpInfo
     *
     * Deletes the record by the values of its key fields.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryDeleteByKeysWithHttpInfo($ids)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryDeleteByKeysRequest($ids);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryDeleteByKeysAsync
     *
     * Deletes the record by the values of its key fields.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryDeleteByKeysAsync($ids)
    {
        return $this->inventorySummaryInquiryDeleteByKeysAsyncWithHttpInfo($ids)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryDeleteByKeysAsyncWithHttpInfo
     *
     * Deletes the record by the values of its key fields.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryDeleteByKeysAsyncWithHttpInfo($ids)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryDeleteByKeysRequest($ids);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryDeleteByKeys'
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryDeleteByKeysRequest($ids)
    {
        // verify the required parameter 'ids' is set
        if ($ids === null || (is_array($ids) && count($ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ids when calling inventorySummaryInquiryDeleteByKeys'
            );
        }

        $resourcePath = '/InventorySummaryInquiry/{ids}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if (is_array($ids)) {
            $ids = ObjectSerializer::serializeCollection($ids, 'pipes');
        }
        if ($ids !== null) {
            $resourcePath = str_replace(
                '{' . 'ids' . '}',
                ObjectSerializer::toPathValue($ids),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryGetAdHocSchema
     *
     * Retrieves the schema of custom fields of the entity from the system.
     *
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel
     */
    public function inventorySummaryInquiryGetAdHocSchema()
    {
        list($response) = $this->inventorySummaryInquiryGetAdHocSchemaWithHttpInfo();
        return $response;
    }

    /**
     * Operation inventorySummaryInquiryGetAdHocSchemaWithHttpInfo
     *
     * Retrieves the schema of custom fields of the entity from the system.
     *
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryGetAdHocSchemaWithHttpInfo()
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetAdHocSchemaRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryGetAdHocSchemaAsync
     *
     * Retrieves the schema of custom fields of the entity from the system.
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetAdHocSchemaAsync()
    {
        return $this->inventorySummaryInquiryGetAdHocSchemaAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryGetAdHocSchemaAsyncWithHttpInfo
     *
     * Retrieves the schema of custom fields of the entity from the system.
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetAdHocSchemaAsyncWithHttpInfo()
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetAdHocSchemaRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryGetAdHocSchema'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryGetAdHocSchemaRequest()
    {

        $resourcePath = '/InventorySummaryInquiry/$adHocSchema';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryGetById
     *
     * Retrieves a record by the value of the session entity ID from the system.
     *
     * @param  string $id The session ID of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel
     */
    public function inventorySummaryInquiryGetById($id, $select = null, $filter = null, $expand = null, $custom = null)
    {
        list($response) = $this->inventorySummaryInquiryGetByIdWithHttpInfo($id, $select, $filter, $expand, $custom);
        return $response;
    }

    /**
     * Operation inventorySummaryInquiryGetByIdWithHttpInfo
     *
     * Retrieves a record by the value of the session entity ID from the system.
     *
     * @param  string $id The session ID of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryGetByIdWithHttpInfo($id, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetByIdRequest($id, $select, $filter, $expand, $custom);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryGetByIdAsync
     *
     * Retrieves a record by the value of the session entity ID from the system.
     *
     * @param  string $id The session ID of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetByIdAsync($id, $select = null, $filter = null, $expand = null, $custom = null)
    {
        return $this->inventorySummaryInquiryGetByIdAsyncWithHttpInfo($id, $select, $filter, $expand, $custom)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryGetByIdAsyncWithHttpInfo
     *
     * Retrieves a record by the value of the session entity ID from the system.
     *
     * @param  string $id The session ID of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetByIdAsyncWithHttpInfo($id, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetByIdRequest($id, $select, $filter, $expand, $custom);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryGetById'
     *
     * @param  string $id The session ID of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryGetByIdRequest($id, $select = null, $filter = null, $expand = null, $custom = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling inventorySummaryInquiryGetById'
            );
        }

        $resourcePath = '/InventorySummaryInquiry/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($select !== null) {
            $queryParams['$select'] = ObjectSerializer::toQueryValue($select);
        }
        // query params
        if ($filter !== null) {
            $queryParams['$filter'] = ObjectSerializer::toQueryValue($filter);
        }
        // query params
        if ($expand !== null) {
            $queryParams['$expand'] = ObjectSerializer::toQueryValue($expand);
        }
        // query params
        if ($custom !== null) {
            $queryParams['$custom'] = ObjectSerializer::toQueryValue($custom);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryGetByKeys
     *
     * Retrieves a record by the values of its key fields from the system.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel
     */
    public function inventorySummaryInquiryGetByKeys($ids, $select = null, $filter = null, $expand = null, $custom = null)
    {
        list($response) = $this->inventorySummaryInquiryGetByKeysWithHttpInfo($ids, $select, $filter, $expand, $custom);
        return $response;
    }

    /**
     * Operation inventorySummaryInquiryGetByKeysWithHttpInfo
     *
     * Retrieves a record by the values of its key fields from the system.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryGetByKeysWithHttpInfo($ids, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetByKeysRequest($ids, $select, $filter, $expand, $custom);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryGetByKeysAsync
     *
     * Retrieves a record by the values of its key fields from the system.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetByKeysAsync($ids, $select = null, $filter = null, $expand = null, $custom = null)
    {
        return $this->inventorySummaryInquiryGetByKeysAsyncWithHttpInfo($ids, $select, $filter, $expand, $custom)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryGetByKeysAsyncWithHttpInfo
     *
     * Retrieves a record by the values of its key fields from the system.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetByKeysAsyncWithHttpInfo($ids, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryGetByKeysRequest($ids, $select, $filter, $expand, $custom);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryGetByKeys'
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryGetByKeysRequest($ids, $select = null, $filter = null, $expand = null, $custom = null)
    {
        // verify the required parameter 'ids' is set
        if ($ids === null || (is_array($ids) && count($ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ids when calling inventorySummaryInquiryGetByKeys'
            );
        }

        $resourcePath = '/InventorySummaryInquiry/{ids}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($select !== null) {
            $queryParams['$select'] = ObjectSerializer::toQueryValue($select);
        }
        // query params
        if ($filter !== null) {
            $queryParams['$filter'] = ObjectSerializer::toQueryValue($filter);
        }
        // query params
        if ($expand !== null) {
            $queryParams['$expand'] = ObjectSerializer::toQueryValue($expand);
        }
        // query params
        if ($custom !== null) {
            $queryParams['$custom'] = ObjectSerializer::toQueryValue($custom);
        }

        // path params
        if (is_array($ids)) {
            $ids = ObjectSerializer::serializeCollection($ids, 'pipes');
        }
        if ($ids !== null) {
            $resourcePath = str_replace(
                '{' . 'ids' . '}',
                ObjectSerializer::toPathValue($ids),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryGetList
     *
     * Retrieves records that satisfy the specified conditions from the system.
     *
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     * @param  int $skip The number of records to be skipped from the list of returned records. (optional)
     * @param  int $top The number of records to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel[]
     */
    public function inventorySummaryInquiryGetList($select = null, $filter = null, $expand = null, $custom = null, $skip = null, $top = null)
    {
        list($response) = $this->inventorySummaryInquiryGetListWithHttpInfo($select, $filter, $expand, $custom, $skip, $top);
        return $response;
    }

    /**
     * Operation inventorySummaryInquiryGetListWithHttpInfo
     *
     * Retrieves records that satisfy the specified conditions from the system.
     *
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     * @param  int $skip The number of records to be skipped from the list of returned records. (optional)
     * @param  int $top The number of records to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryGetListWithHttpInfo($select = null, $filter = null, $expand = null, $custom = null, $skip = null, $top = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel[]';
        $request = $this->inventorySummaryInquiryGetListRequest($select, $filter, $expand, $custom, $skip, $top);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryGetListAsync
     *
     * Retrieves records that satisfy the specified conditions from the system.
     *
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     * @param  int $skip The number of records to be skipped from the list of returned records. (optional)
     * @param  int $top The number of records to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetListAsync($select = null, $filter = null, $expand = null, $custom = null, $skip = null, $top = null)
    {
        return $this->inventorySummaryInquiryGetListAsyncWithHttpInfo($select, $filter, $expand, $custom, $skip, $top)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryGetListAsyncWithHttpInfo
     *
     * Retrieves records that satisfy the specified conditions from the system.
     *
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     * @param  int $skip The number of records to be skipped from the list of returned records. (optional)
     * @param  int $top The number of records to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryGetListAsyncWithHttpInfo($select = null, $filter = null, $expand = null, $custom = null, $skip = null, $top = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel[]';
        $request = $this->inventorySummaryInquiryGetListRequest($select, $filter, $expand, $custom, $skip, $top);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryGetList'
     *
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     * @param  int $skip The number of records to be skipped from the list of returned records. (optional)
     * @param  int $top The number of records to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryGetListRequest($select = null, $filter = null, $expand = null, $custom = null, $skip = null, $top = null)
    {

        $resourcePath = '/InventorySummaryInquiry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($select !== null) {
            $queryParams['$select'] = ObjectSerializer::toQueryValue($select);
        }
        // query params
        if ($filter !== null) {
            $queryParams['$filter'] = ObjectSerializer::toQueryValue($filter);
        }
        // query params
        if ($expand !== null) {
            $queryParams['$expand'] = ObjectSerializer::toQueryValue($expand);
        }
        // query params
        if ($custom !== null) {
            $queryParams['$custom'] = ObjectSerializer::toQueryValue($custom);
        }
        // query params
        if ($skip !== null) {
            $queryParams['$skip'] = ObjectSerializer::toQueryValue($skip);
        }
        // query params
        if ($top !== null) {
            $queryParams['$top'] = ObjectSerializer::toQueryValue($top);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryPutEntity
     *
     * Creates a record or updates an existing record.
     *
     * @param  \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel $entity The record to be passed to the system. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel
     */
    public function inventorySummaryInquiryPutEntity($entity, $select = null, $filter = null, $expand = null, $custom = null)
    {
        list($response) = $this->inventorySummaryInquiryPutEntityWithHttpInfo($entity, $select, $filter, $expand, $custom);
        return $response;
    }

    /**
     * Operation inventorySummaryInquiryPutEntityWithHttpInfo
     *
     * Creates a record or updates an existing record.
     *
     * @param  \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel $entity The record to be passed to the system. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryPutEntityWithHttpInfo($entity, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryPutEntityRequest($entity, $select, $filter, $expand, $custom);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryPutEntityAsync
     *
     * Creates a record or updates an existing record.
     *
     * @param  \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel $entity The record to be passed to the system. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryPutEntityAsync($entity, $select = null, $filter = null, $expand = null, $custom = null)
    {
        return $this->inventorySummaryInquiryPutEntityAsyncWithHttpInfo($entity, $select, $filter, $expand, $custom)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryPutEntityAsyncWithHttpInfo
     *
     * Creates a record or updates an existing record.
     *
     * @param  \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel $entity The record to be passed to the system. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryPutEntityAsyncWithHttpInfo($entity, $select = null, $filter = null, $expand = null, $custom = null)
    {
        $returnType = '\Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel';
        $request = $this->inventorySummaryInquiryPutEntityRequest($entity, $select, $filter, $expand, $custom);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryPutEntity'
     *
     * @param  \Hut6\CranaplusAcumaticaSdk\Model\InventorySummaryInquiryModel $entity The record to be passed to the system. (required)
     * @param  string $select The fields of the entity to be returned from the system. (optional)
     * @param  string $filter The conditions that determine which records should be selected from the system. (optional)
     * @param  string $expand The linked and detail entities that should be expanded. (optional)
     * @param  string $custom The fields that are not defined in the contract of the endpoint to be returned from the system. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryPutEntityRequest($entity, $select = null, $filter = null, $expand = null, $custom = null)
    {
        // verify the required parameter 'entity' is set
        if ($entity === null || (is_array($entity) && count($entity) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity when calling inventorySummaryInquiryPutEntity'
            );
        }

        $resourcePath = '/InventorySummaryInquiry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($select !== null) {
            $queryParams['$select'] = ObjectSerializer::toQueryValue($select);
        }
        // query params
        if ($filter !== null) {
            $queryParams['$filter'] = ObjectSerializer::toQueryValue($filter);
        }
        // query params
        if ($expand !== null) {
            $queryParams['$expand'] = ObjectSerializer::toQueryValue($expand);
        }
        // query params
        if ($custom !== null) {
            $queryParams['$custom'] = ObjectSerializer::toQueryValue($custom);
        }


        // body params
        $_tempBody = null;
        if (isset($entity)) {
            $_tempBody = $entity;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation inventorySummaryInquiryPutFile
     *
     * Attaches a file to a record.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $filename The name of the file that you are going to attach with the extension. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function inventorySummaryInquiryPutFile($ids, $filename)
    {
        $this->inventorySummaryInquiryPutFileWithHttpInfo($ids, $filename);
    }

    /**
     * Operation inventorySummaryInquiryPutFileWithHttpInfo
     *
     * Attaches a file to a record.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $filename The name of the file that you are going to attach with the extension. (required)
     *
     * @throws \Hut6\CranaplusAcumaticaSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function inventorySummaryInquiryPutFileWithHttpInfo($ids, $filename)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryPutFileRequest($ids, $filename);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hut6\CranaplusAcumaticaSdk\Model\HttpErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation inventorySummaryInquiryPutFileAsync
     *
     * Attaches a file to a record.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $filename The name of the file that you are going to attach with the extension. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryPutFileAsync($ids, $filename)
    {
        return $this->inventorySummaryInquiryPutFileAsyncWithHttpInfo($ids, $filename)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation inventorySummaryInquiryPutFileAsyncWithHttpInfo
     *
     * Attaches a file to a record.
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $filename The name of the file that you are going to attach with the extension. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function inventorySummaryInquiryPutFileAsyncWithHttpInfo($ids, $filename)
    {
        $returnType = '';
        $request = $this->inventorySummaryInquiryPutFileRequest($ids, $filename);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'inventorySummaryInquiryPutFile'
     *
     * @param  string[] $ids The values of the key fields of the record. (required)
     * @param  string $filename The name of the file that you are going to attach with the extension. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function inventorySummaryInquiryPutFileRequest($ids, $filename)
    {
        // verify the required parameter 'ids' is set
        if ($ids === null || (is_array($ids) && count($ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ids when calling inventorySummaryInquiryPutFile'
            );
        }
        // verify the required parameter 'filename' is set
        if ($filename === null || (is_array($filename) && count($filename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filename when calling inventorySummaryInquiryPutFile'
            );
        }

        $resourcePath = '/InventorySummaryInquiry/{ids}/files/{filename}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if (is_array($ids)) {
            $ids = ObjectSerializer::serializeCollection($ids, 'pipes');
        }
        if ($ids !== null) {
            $resourcePath = str_replace(
                '{' . 'ids' . '}',
                ObjectSerializer::toPathValue($ids),
                $resourcePath
            );
        }
        // path params
        if ($filename !== null) {
            $resourcePath = str_replace(
                '{' . 'filename' . '}',
                ObjectSerializer::toPathValue($filename),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
