<?php
/**
 * EmployeeModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Crana/17.200.001
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Hut6\CranaplusAcumaticaSdk\Model;
use \Hut6\CranaplusAcumaticaSdk\ObjectSerializer;

/**
 * EmployeeModel Class Doc Comment
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployeeModel extends EntityModel 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Employee';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'email' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'fax' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'firstName' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'lastName' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone1' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone1Type' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone2' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone2Type' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone3' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'phone3Type' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'title' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'financialSettings' => '\Hut6\CranaplusAcumaticaSdk\Model\FinancialSettingModel',
        'branchID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'contact' => '\Hut6\CranaplusAcumaticaSdk\Model\ContactModel',
        'currencyID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'dateOfBirth' => '\Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel',
        'departmentID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'employeeClassID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'employeeCost' => '\Hut6\CranaplusAcumaticaSdk\Model\EmployeeCostRecordModel[]',
        'employeeID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'employmentHistory' => '\Hut6\CranaplusAcumaticaSdk\Model\EmploymentHistoryRecordModel[]',
        'name' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'paymentMethod' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'reportsToID' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'status' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'email' => null,
        'fax' => null,
        'firstName' => null,
        'lastName' => null,
        'phone1' => null,
        'phone1Type' => null,
        'phone2' => null,
        'phone2Type' => null,
        'phone3' => null,
        'phone3Type' => null,
        'title' => null,
        'financialSettings' => null,
        'branchID' => null,
        'contact' => null,
        'currencyID' => null,
        'dateOfBirth' => null,
        'departmentID' => null,
        'employeeClassID' => null,
        'employeeCost' => null,
        'employeeID' => null,
        'employmentHistory' => null,
        'name' => null,
        'paymentMethod' => null,
        'reportsToID' => null,
        'status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'Email',
        'fax' => 'Fax',
        'firstName' => 'FirstName',
        'lastName' => 'LastName',
        'phone1' => 'Phone1',
        'phone1Type' => 'Phone1Type',
        'phone2' => 'Phone2',
        'phone2Type' => 'Phone2Type',
        'phone3' => 'Phone3',
        'phone3Type' => 'Phone3Type',
        'title' => 'Title',
        'financialSettings' => 'FinancialSettings',
        'branchID' => 'BranchID',
        'contact' => 'Contact',
        'currencyID' => 'CurrencyID',
        'dateOfBirth' => 'DateOfBirth',
        'departmentID' => 'DepartmentID',
        'employeeClassID' => 'EmployeeClassID',
        'employeeCost' => 'EmployeeCost',
        'employeeID' => 'EmployeeID',
        'employmentHistory' => 'EmploymentHistory',
        'name' => 'Name',
        'paymentMethod' => 'PaymentMethod',
        'reportsToID' => 'ReportsToID',
        'status' => 'Status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'fax' => 'setFax',
        'firstName' => 'setFirstName',
        'lastName' => 'setLastName',
        'phone1' => 'setPhone1',
        'phone1Type' => 'setPhone1Type',
        'phone2' => 'setPhone2',
        'phone2Type' => 'setPhone2Type',
        'phone3' => 'setPhone3',
        'phone3Type' => 'setPhone3Type',
        'title' => 'setTitle',
        'financialSettings' => 'setFinancialSettings',
        'branchID' => 'setBranchID',
        'contact' => 'setContact',
        'currencyID' => 'setCurrencyID',
        'dateOfBirth' => 'setDateOfBirth',
        'departmentID' => 'setDepartmentID',
        'employeeClassID' => 'setEmployeeClassID',
        'employeeCost' => 'setEmployeeCost',
        'employeeID' => 'setEmployeeID',
        'employmentHistory' => 'setEmploymentHistory',
        'name' => 'setName',
        'paymentMethod' => 'setPaymentMethod',
        'reportsToID' => 'setReportsToID',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'fax' => 'getFax',
        'firstName' => 'getFirstName',
        'lastName' => 'getLastName',
        'phone1' => 'getPhone1',
        'phone1Type' => 'getPhone1Type',
        'phone2' => 'getPhone2',
        'phone2Type' => 'getPhone2Type',
        'phone3' => 'getPhone3',
        'phone3Type' => 'getPhone3Type',
        'title' => 'getTitle',
        'financialSettings' => 'getFinancialSettings',
        'branchID' => 'getBranchID',
        'contact' => 'getContact',
        'currencyID' => 'getCurrencyID',
        'dateOfBirth' => 'getDateOfBirth',
        'departmentID' => 'getDepartmentID',
        'employeeClassID' => 'getEmployeeClassID',
        'employeeCost' => 'getEmployeeCost',
        'employeeID' => 'getEmployeeID',
        'employmentHistory' => 'getEmploymentHistory',
        'name' => 'getName',
        'paymentMethod' => 'getPaymentMethod',
        'reportsToID' => 'getReportsToID',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['fax'] = isset($data['fax']) ? $data['fax'] : null;
        $this->container['firstName'] = isset($data['firstName']) ? $data['firstName'] : null;
        $this->container['lastName'] = isset($data['lastName']) ? $data['lastName'] : null;
        $this->container['phone1'] = isset($data['phone1']) ? $data['phone1'] : null;
        $this->container['phone1Type'] = isset($data['phone1Type']) ? $data['phone1Type'] : null;
        $this->container['phone2'] = isset($data['phone2']) ? $data['phone2'] : null;
        $this->container['phone2Type'] = isset($data['phone2Type']) ? $data['phone2Type'] : null;
        $this->container['phone3'] = isset($data['phone3']) ? $data['phone3'] : null;
        $this->container['phone3Type'] = isset($data['phone3Type']) ? $data['phone3Type'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['financialSettings'] = isset($data['financialSettings']) ? $data['financialSettings'] : null;
        $this->container['branchID'] = isset($data['branchID']) ? $data['branchID'] : null;
        $this->container['contact'] = isset($data['contact']) ? $data['contact'] : null;
        $this->container['currencyID'] = isset($data['currencyID']) ? $data['currencyID'] : null;
        $this->container['dateOfBirth'] = isset($data['dateOfBirth']) ? $data['dateOfBirth'] : null;
        $this->container['departmentID'] = isset($data['departmentID']) ? $data['departmentID'] : null;
        $this->container['employeeClassID'] = isset($data['employeeClassID']) ? $data['employeeClassID'] : null;
        $this->container['employeeCost'] = isset($data['employeeCost']) ? $data['employeeCost'] : null;
        $this->container['employeeID'] = isset($data['employeeID']) ? $data['employeeID'] : null;
        $this->container['employmentHistory'] = isset($data['employmentHistory']) ? $data['employmentHistory'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['paymentMethod'] = isset($data['paymentMethod']) ? $data['paymentMethod'] : null;
        $this->container['reportsToID'] = isset($data['reportsToID']) ? $data['reportsToID'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $fax fax
     *
     * @return $this
     */
    public function setFax($fax)
    {
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $firstName firstName
     *
     * @return $this
     */
    public function setFirstName($firstName)
    {
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $lastName lastName
     *
     * @return $this
     */
    public function setLastName($lastName)
    {
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets phone1
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone1()
    {
        return $this->container['phone1'];
    }

    /**
     * Sets phone1
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone1 phone1
     *
     * @return $this
     */
    public function setPhone1($phone1)
    {
        $this->container['phone1'] = $phone1;

        return $this;
    }

    /**
     * Gets phone1Type
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone1Type()
    {
        return $this->container['phone1Type'];
    }

    /**
     * Sets phone1Type
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone1Type phone1Type
     *
     * @return $this
     */
    public function setPhone1Type($phone1Type)
    {
        $this->container['phone1Type'] = $phone1Type;

        return $this;
    }

    /**
     * Gets phone2
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone2()
    {
        return $this->container['phone2'];
    }

    /**
     * Sets phone2
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone2 phone2
     *
     * @return $this
     */
    public function setPhone2($phone2)
    {
        $this->container['phone2'] = $phone2;

        return $this;
    }

    /**
     * Gets phone2Type
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone2Type()
    {
        return $this->container['phone2Type'];
    }

    /**
     * Sets phone2Type
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone2Type phone2Type
     *
     * @return $this
     */
    public function setPhone2Type($phone2Type)
    {
        $this->container['phone2Type'] = $phone2Type;

        return $this;
    }

    /**
     * Gets phone3
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone3()
    {
        return $this->container['phone3'];
    }

    /**
     * Sets phone3
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone3 phone3
     *
     * @return $this
     */
    public function setPhone3($phone3)
    {
        $this->container['phone3'] = $phone3;

        return $this;
    }

    /**
     * Gets phone3Type
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPhone3Type()
    {
        return $this->container['phone3Type'];
    }

    /**
     * Sets phone3Type
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $phone3Type phone3Type
     *
     * @return $this
     */
    public function setPhone3Type($phone3Type)
    {
        $this->container['phone3Type'] = $phone3Type;

        return $this;
    }

    /**
     * Gets title
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets financialSettings
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\FinancialSettingModel
     */
    public function getFinancialSettings()
    {
        return $this->container['financialSettings'];
    }

    /**
     * Sets financialSettings
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\FinancialSettingModel $financialSettings financialSettings
     *
     * @return $this
     */
    public function setFinancialSettings($financialSettings)
    {
        $this->container['financialSettings'] = $financialSettings;

        return $this;
    }

    /**
     * Gets branchID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getBranchID()
    {
        return $this->container['branchID'];
    }

    /**
     * Sets branchID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $branchID branchID
     *
     * @return $this
     */
    public function setBranchID($branchID)
    {
        $this->container['branchID'] = $branchID;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\ContactModel
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\ContactModel $contact contact
     *
     * @return $this
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets currencyID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getCurrencyID()
    {
        return $this->container['currencyID'];
    }

    /**
     * Sets currencyID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $currencyID currencyID
     *
     * @return $this
     */
    public function setCurrencyID($currencyID)
    {
        $this->container['currencyID'] = $currencyID;

        return $this;
    }

    /**
     * Gets dateOfBirth
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel
     */
    public function getDateOfBirth()
    {
        return $this->container['dateOfBirth'];
    }

    /**
     * Sets dateOfBirth
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel $dateOfBirth dateOfBirth
     *
     * @return $this
     */
    public function setDateOfBirth($dateOfBirth)
    {
        $this->container['dateOfBirth'] = $dateOfBirth;

        return $this;
    }

    /**
     * Gets departmentID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getDepartmentID()
    {
        return $this->container['departmentID'];
    }

    /**
     * Sets departmentID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $departmentID departmentID
     *
     * @return $this
     */
    public function setDepartmentID($departmentID)
    {
        $this->container['departmentID'] = $departmentID;

        return $this;
    }

    /**
     * Gets employeeClassID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getEmployeeClassID()
    {
        return $this->container['employeeClassID'];
    }

    /**
     * Sets employeeClassID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $employeeClassID employeeClassID
     *
     * @return $this
     */
    public function setEmployeeClassID($employeeClassID)
    {
        $this->container['employeeClassID'] = $employeeClassID;

        return $this;
    }

    /**
     * Gets employeeCost
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\EmployeeCostRecordModel[]
     */
    public function getEmployeeCost()
    {
        return $this->container['employeeCost'];
    }

    /**
     * Sets employeeCost
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\EmployeeCostRecordModel[] $employeeCost employeeCost
     *
     * @return $this
     */
    public function setEmployeeCost($employeeCost)
    {
        $this->container['employeeCost'] = $employeeCost;

        return $this;
    }

    /**
     * Gets employeeID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getEmployeeID()
    {
        return $this->container['employeeID'];
    }

    /**
     * Sets employeeID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $employeeID employeeID
     *
     * @return $this
     */
    public function setEmployeeID($employeeID)
    {
        $this->container['employeeID'] = $employeeID;

        return $this;
    }

    /**
     * Gets employmentHistory
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\EmploymentHistoryRecordModel[]
     */
    public function getEmploymentHistory()
    {
        return $this->container['employmentHistory'];
    }

    /**
     * Sets employmentHistory
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\EmploymentHistoryRecordModel[] $employmentHistory employmentHistory
     *
     * @return $this
     */
    public function setEmploymentHistory($employmentHistory)
    {
        $this->container['employmentHistory'] = $employmentHistory;

        return $this;
    }

    /**
     * Gets name
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets paymentMethod
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPaymentMethod()
    {
        return $this->container['paymentMethod'];
    }

    /**
     * Sets paymentMethod
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $paymentMethod paymentMethod
     *
     * @return $this
     */
    public function setPaymentMethod($paymentMethod)
    {
        $this->container['paymentMethod'] = $paymentMethod;

        return $this;
    }

    /**
     * Gets reportsToID
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getReportsToID()
    {
        return $this->container['reportsToID'];
    }

    /**
     * Sets reportsToID
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $reportsToID reportsToID
     *
     * @return $this
     */
    public function setReportsToID($reportsToID)
    {
        $this->container['reportsToID'] = $reportsToID;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


