<?php
/**
 * FinancialSettingsModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Crana/17.200.001
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Hut6\CranaplusAcumaticaSdk\Model;

use \ArrayAccess;
use \Hut6\CranaplusAcumaticaSdk\ObjectSerializer;

/**
 * FinancialSettingsModel Class Doc Comment
 *
 * @category Class
 * @package  Hut6\CranaplusAcumaticaSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FinancialSettingsModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FinancialSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'rowNumber' => 'int',
        'note' => 'string',
        'custom' => 'map[string,map[string,\Hut6\CranaplusAcumaticaSdk\Model\CustomFieldModel]]',
        'files' => '\Hut6\CranaplusAcumaticaSdk\Model\FileLinkModel[]',
        'billSeparately' => '\Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel',
        'branch' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'cashDiscountDate' => '\Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel',
        'customerTaxZone' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'dueDate' => '\Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel',
        'entityUsageType' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'invoiceDate' => '\Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel',
        'invoiceNbr' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'originalOrderNbr' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'originalOrderType' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'overrideTaxZone' => '\Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel',
        'owner' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'postPeriod' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel',
        'terms' => '\Hut6\CranaplusAcumaticaSdk\Model\StringValueModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'uuid',
        'rowNumber' => 'int64',
        'note' => null,
        'custom' => null,
        'files' => null,
        'billSeparately' => null,
        'branch' => null,
        'cashDiscountDate' => null,
        'customerTaxZone' => null,
        'dueDate' => null,
        'entityUsageType' => null,
        'invoiceDate' => null,
        'invoiceNbr' => null,
        'originalOrderNbr' => null,
        'originalOrderType' => null,
        'overrideTaxZone' => null,
        'owner' => null,
        'postPeriod' => null,
        'terms' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'rowNumber' => 'rowNumber',
        'note' => 'note',
        'custom' => 'custom',
        'files' => 'files',
        'billSeparately' => 'BillSeparately',
        'branch' => 'Branch',
        'cashDiscountDate' => 'CashDiscountDate',
        'customerTaxZone' => 'CustomerTaxZone',
        'dueDate' => 'DueDate',
        'entityUsageType' => 'EntityUsageType',
        'invoiceDate' => 'InvoiceDate',
        'invoiceNbr' => 'InvoiceNbr',
        'originalOrderNbr' => 'OriginalOrderNbr',
        'originalOrderType' => 'OriginalOrderType',
        'overrideTaxZone' => 'OverrideTaxZone',
        'owner' => 'Owner',
        'postPeriod' => 'PostPeriod',
        'terms' => 'Terms'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'rowNumber' => 'setRowNumber',
        'note' => 'setNote',
        'custom' => 'setCustom',
        'files' => 'setFiles',
        'billSeparately' => 'setBillSeparately',
        'branch' => 'setBranch',
        'cashDiscountDate' => 'setCashDiscountDate',
        'customerTaxZone' => 'setCustomerTaxZone',
        'dueDate' => 'setDueDate',
        'entityUsageType' => 'setEntityUsageType',
        'invoiceDate' => 'setInvoiceDate',
        'invoiceNbr' => 'setInvoiceNbr',
        'originalOrderNbr' => 'setOriginalOrderNbr',
        'originalOrderType' => 'setOriginalOrderType',
        'overrideTaxZone' => 'setOverrideTaxZone',
        'owner' => 'setOwner',
        'postPeriod' => 'setPostPeriod',
        'terms' => 'setTerms'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'rowNumber' => 'getRowNumber',
        'note' => 'getNote',
        'custom' => 'getCustom',
        'files' => 'getFiles',
        'billSeparately' => 'getBillSeparately',
        'branch' => 'getBranch',
        'cashDiscountDate' => 'getCashDiscountDate',
        'customerTaxZone' => 'getCustomerTaxZone',
        'dueDate' => 'getDueDate',
        'entityUsageType' => 'getEntityUsageType',
        'invoiceDate' => 'getInvoiceDate',
        'invoiceNbr' => 'getInvoiceNbr',
        'originalOrderNbr' => 'getOriginalOrderNbr',
        'originalOrderType' => 'getOriginalOrderType',
        'overrideTaxZone' => 'getOverrideTaxZone',
        'owner' => 'getOwner',
        'postPeriod' => 'getPostPeriod',
        'terms' => 'getTerms'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['rowNumber'] = isset($data['rowNumber']) ? $data['rowNumber'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['custom'] = isset($data['custom']) ? $data['custom'] : null;
        $this->container['files'] = isset($data['files']) ? $data['files'] : null;
        $this->container['billSeparately'] = isset($data['billSeparately']) ? $data['billSeparately'] : null;
        $this->container['branch'] = isset($data['branch']) ? $data['branch'] : null;
        $this->container['cashDiscountDate'] = isset($data['cashDiscountDate']) ? $data['cashDiscountDate'] : null;
        $this->container['customerTaxZone'] = isset($data['customerTaxZone']) ? $data['customerTaxZone'] : null;
        $this->container['dueDate'] = isset($data['dueDate']) ? $data['dueDate'] : null;
        $this->container['entityUsageType'] = isset($data['entityUsageType']) ? $data['entityUsageType'] : null;
        $this->container['invoiceDate'] = isset($data['invoiceDate']) ? $data['invoiceDate'] : null;
        $this->container['invoiceNbr'] = isset($data['invoiceNbr']) ? $data['invoiceNbr'] : null;
        $this->container['originalOrderNbr'] = isset($data['originalOrderNbr']) ? $data['originalOrderNbr'] : null;
        $this->container['originalOrderType'] = isset($data['originalOrderType']) ? $data['originalOrderType'] : null;
        $this->container['overrideTaxZone'] = isset($data['overrideTaxZone']) ? $data['overrideTaxZone'] : null;
        $this->container['owner'] = isset($data['owner']) ? $data['owner'] : null;
        $this->container['postPeriod'] = isset($data['postPeriod']) ? $data['postPeriod'] : null;
        $this->container['terms'] = isset($data['terms']) ? $data['terms'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets rowNumber
     *
     * @return int
     */
    public function getRowNumber()
    {
        return $this->container['rowNumber'];
    }

    /**
     * Sets rowNumber
     *
     * @param int $rowNumber rowNumber
     *
     * @return $this
     */
    public function setRowNumber($rowNumber)
    {
        $this->container['rowNumber'] = $rowNumber;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets custom
     *
     * @return map[string,map[string,\Hut6\CranaplusAcumaticaSdk\Model\CustomFieldModel]]
     */
    public function getCustom()
    {
        return $this->container['custom'];
    }

    /**
     * Sets custom
     *
     * @param map[string,map[string,\Hut6\CranaplusAcumaticaSdk\Model\CustomFieldModel]] $custom custom
     *
     * @return $this
     */
    public function setCustom($custom)
    {
        $this->container['custom'] = $custom;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\FileLinkModel[]
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\FileLinkModel[] $files files
     *
     * @return $this
     */
    public function setFiles($files)
    {
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets billSeparately
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel
     */
    public function getBillSeparately()
    {
        return $this->container['billSeparately'];
    }

    /**
     * Sets billSeparately
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel $billSeparately billSeparately
     *
     * @return $this
     */
    public function setBillSeparately($billSeparately)
    {
        $this->container['billSeparately'] = $billSeparately;

        return $this;
    }

    /**
     * Gets branch
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getBranch()
    {
        return $this->container['branch'];
    }

    /**
     * Sets branch
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $branch branch
     *
     * @return $this
     */
    public function setBranch($branch)
    {
        $this->container['branch'] = $branch;

        return $this;
    }

    /**
     * Gets cashDiscountDate
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel
     */
    public function getCashDiscountDate()
    {
        return $this->container['cashDiscountDate'];
    }

    /**
     * Sets cashDiscountDate
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel $cashDiscountDate cashDiscountDate
     *
     * @return $this
     */
    public function setCashDiscountDate($cashDiscountDate)
    {
        $this->container['cashDiscountDate'] = $cashDiscountDate;

        return $this;
    }

    /**
     * Gets customerTaxZone
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getCustomerTaxZone()
    {
        return $this->container['customerTaxZone'];
    }

    /**
     * Sets customerTaxZone
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $customerTaxZone customerTaxZone
     *
     * @return $this
     */
    public function setCustomerTaxZone($customerTaxZone)
    {
        $this->container['customerTaxZone'] = $customerTaxZone;

        return $this;
    }

    /**
     * Gets dueDate
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel
     */
    public function getDueDate()
    {
        return $this->container['dueDate'];
    }

    /**
     * Sets dueDate
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel $dueDate dueDate
     *
     * @return $this
     */
    public function setDueDate($dueDate)
    {
        $this->container['dueDate'] = $dueDate;

        return $this;
    }

    /**
     * Gets entityUsageType
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getEntityUsageType()
    {
        return $this->container['entityUsageType'];
    }

    /**
     * Sets entityUsageType
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $entityUsageType entityUsageType
     *
     * @return $this
     */
    public function setEntityUsageType($entityUsageType)
    {
        $this->container['entityUsageType'] = $entityUsageType;

        return $this;
    }

    /**
     * Gets invoiceDate
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel
     */
    public function getInvoiceDate()
    {
        return $this->container['invoiceDate'];
    }

    /**
     * Sets invoiceDate
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\DateTimeValueModel $invoiceDate invoiceDate
     *
     * @return $this
     */
    public function setInvoiceDate($invoiceDate)
    {
        $this->container['invoiceDate'] = $invoiceDate;

        return $this;
    }

    /**
     * Gets invoiceNbr
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getInvoiceNbr()
    {
        return $this->container['invoiceNbr'];
    }

    /**
     * Sets invoiceNbr
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $invoiceNbr invoiceNbr
     *
     * @return $this
     */
    public function setInvoiceNbr($invoiceNbr)
    {
        $this->container['invoiceNbr'] = $invoiceNbr;

        return $this;
    }

    /**
     * Gets originalOrderNbr
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getOriginalOrderNbr()
    {
        return $this->container['originalOrderNbr'];
    }

    /**
     * Sets originalOrderNbr
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $originalOrderNbr originalOrderNbr
     *
     * @return $this
     */
    public function setOriginalOrderNbr($originalOrderNbr)
    {
        $this->container['originalOrderNbr'] = $originalOrderNbr;

        return $this;
    }

    /**
     * Gets originalOrderType
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getOriginalOrderType()
    {
        return $this->container['originalOrderType'];
    }

    /**
     * Sets originalOrderType
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $originalOrderType originalOrderType
     *
     * @return $this
     */
    public function setOriginalOrderType($originalOrderType)
    {
        $this->container['originalOrderType'] = $originalOrderType;

        return $this;
    }

    /**
     * Gets overrideTaxZone
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel
     */
    public function getOverrideTaxZone()
    {
        return $this->container['overrideTaxZone'];
    }

    /**
     * Sets overrideTaxZone
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\BooleanValueModel $overrideTaxZone overrideTaxZone
     *
     * @return $this
     */
    public function setOverrideTaxZone($overrideTaxZone)
    {
        $this->container['overrideTaxZone'] = $overrideTaxZone;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $owner owner
     *
     * @return $this
     */
    public function setOwner($owner)
    {
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets postPeriod
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getPostPeriod()
    {
        return $this->container['postPeriod'];
    }

    /**
     * Sets postPeriod
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $postPeriod postPeriod
     *
     * @return $this
     */
    public function setPostPeriod($postPeriod)
    {
        $this->container['postPeriod'] = $postPeriod;

        return $this;
    }

    /**
     * Gets terms
     *
     * @return \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel
     */
    public function getTerms()
    {
        return $this->container['terms'];
    }

    /**
     * Sets terms
     *
     * @param \Hut6\CranaplusAcumaticaSdk\Model\StringValueModel $terms terms
     *
     * @return $this
     */
    public function setTerms($terms)
    {
        $this->container['terms'] = $terms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


